---
version: "3.9"

x-image:
  image: &image ghcr.io/woozymasta/guassp:latest

x-api: &api
  image: *image
  command: api
  env_file:
    - docker-compose.env
  depends_on:
    redis:
      condition: service_healthy
  healthcheck:
    test: ["CMD", "curl", "-Lsf", "0.0.0.0:5000/health"]
    interval: 1s
    timeout: 3s
    retries: 10

x-worker: &worker
    image: *image
    command: worker
    env_file:
      - docker-compose.env
    depends_on:
      redis:
        condition: service_healthy

services:

  api-1:
    <<: *api
    ports:
      - 8000:5000
  api-2:
    <<: *api
    ports:
      - 8001:5000

  worker-0:
    <<: *worker
  worker-1:
    <<: *worker
  worker-2:
    <<: *worker
  worker-3:
    <<: *worker
  worker-4:
    <<: *worker
  worker-5:
    <<: *worker
  worker-6:
    <<: *worker
  worker-7:
    <<: *worker
  worker-8:
    <<: *worker
  worker-9:
    <<: *worker

  exporter:
    image: ghcr.io/woozymasta/guassp:latest
    command: exporter
    env_file:
      - docker-compose.env
    ports:
      - 9726:9726
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: docker.io/redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 10

  redis-exporter:
    image: bitnami/redis-exporter:latest
    env_file:
      - docker-compose.env
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - 9121:9121
