{
 "title": "GitLab to SonarQube permissions",
 "description": "Dashboard for GitLab to SonarQube permissions sync based on Python RQ",
 "tags": [
  "prometheus",
  "rq",
  "python-rq",
  "sonarqube",
  "gitlab"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({__name__=~\"rq_.*\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({__name__=~\"rq_.*\"}, instance)"
   },
   {
    "name": "queue",
    "label": "Queue",
    "query": "label_values({__name__=~\"rq_.*\"}, queue)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RQ workers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(rq_workers{job=\"$job\", instance=\"$instance\"}) or vector(0)",
     "legendFormat": "Workers"
    }
   ]
  },
  {
   "title": "Workers capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(count(rq_workers{state=\"busy\", job=\"$job\", instance=\"$instance\"}) / count(rq_workers{job=\"$job\", instance=\"$instance\"})) * 100",
     "legendFormat": "Busy workers"
    },
    {
     "expr": "(count(rq_workers{state=\"idle\", job=\"$job\", instance=\"$instance\"}) / count(rq_workers{job=\"$job\", instance=\"$instance\"})) * 100",
     "legendFormat": "Idle workers"
    }
   ]
  },
  {
   "title": "Current jobs overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum(rq_jobs{status=\"queued\", job=\"$job\", instance=\"$instance\"}) by (queue)"
    },
    {
     "expr": "sum(rq_jobs{status=\"started\", job=\"$job\", instance=\"$instance\"}) by (queue)"
    },
    {
     "expr": "sum(rq_jobs{status=\"finished\", job=\"$job\", instance=\"$instance\"}) by (queue)"
    },
    {
     "expr": "sum(rq_jobs{status=\"failed\", job=\"$job\", instance=\"$instance\"}) by (queue)"
    },
    {
     "expr": "sum(rq_jobs{status=\"deferred\", job=\"$job\", instance=\"$instance\"}) by (queue)"
    },
    {
     "expr": "sum(rq_jobs{status=\"scheduled\", job=\"$job\", instance=\"$instance\"}) by (queue)"
    }
   ]
  },
  {
   "title": "Avg. data collection duration",
   "type": "singlestat",
   "description": "The average time the exporter took to query the Redis instance for the RQ workers and jobs data.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(rq_request_processing_seconds_sum{job=\"$job\", instance=\"$instance\"}[$__range]) /rate(rq_request_processing_seconds_count{job=\"$job\", instance=\"$instance\"}[$__range])"
    }
   ]
  },
  { "title": "Jobs by status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Queued",
   "type": "singlestat",
   "description": "This percentage reflects the number of jobs currently queued, an optimal value is a value near or equal to 0% which means the jobs are being picked up by the workers without delays.\n\nA high percentage of queued jobs means that you need to add more workers as the current workers are not able to process all the jobs in a timely manner.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rq_jobs{status=\"queued\", job=\"$job\", instance=\"$instance\", queue=~\"$queue\"}) / sum(rq_jobs{job=\"$job\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Started",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 10 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rq_jobs{status=\"started\", job=\"$job\", instance=\"$instance\", queue=~\"$queue\"}) / sum(rq_jobs{job=\"$job\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Finished",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 10 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rq_jobs{status=\"finished\", job=\"$job\", instance=\"$instance\", queue=~\"$queue\"}) / sum(rq_jobs{job=\"$job\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "description": "The percentage of failed jobs will always be higher if you are using the default failure TTL  which is 1 year and you don't re-queue the jobs.\n\nIf you don't intend to re-queue the jobs you should set a lower failure TTL.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 10 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rq_jobs{status=\"failed\", job=\"$job\", instance=\"$instance\", queue=~\"$queue\"}) / sum(rq_jobs{job=\"$job\", instance=\"$instance\"})"
    },
    {}
   ]
  },
  {
   "title": "Deferred",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 10 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rq_jobs{status=\"deferred\", job=\"$job\", instance=\"$instance\", queue=~\"$queue\"}) / sum(rq_jobs{job=\"$job\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Scheduled",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 10 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rq_jobs{status=\"scheduled\", job=\"$job\", instance=\"$instance\", queue=~\"$queue\"}) / sum(rq_jobs{job=\"$job\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Percentage of jobs by status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rq_jobs{job=\"$job\", instance=\"$instance\", queue=~\"$queue\"}) / ignoring(status) group_left sum(rq_jobs{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Number of jobs by status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rq_jobs{job=\"$job\", instance=\"$instance\", queue=~\"$queue\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Jobs by queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Percentage of jobs by queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) (rq_jobs{job=\"$job\", instance=\"$instance\"}) / ignoring(queue) group_left sum(rq_jobs{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Number of jobs by queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rq_jobs{job=\"$job\", instance=\"$instance\"}) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  { "title": "Jobs by status and queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Percentage of jobs by status and queue",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (status, queue) (rq_jobs{job=\"$job\", instance=\"$instance\"}) / ignoring(status) group_left sum by (queue) (rq_jobs{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "{{queue}} ({{status}})"
    }
   ]
  },
  {
   "title": "Number of jobs by status and queue",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rq_jobs{job=\"$job\", instance=\"$instance\"}) by (queue, status)",
     "legendFormat": "{{queue}} ({{status}})"
    }
   ]
  }
 ]
}